#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-stream-lib
Version  : 2.7.0
Release  : 1
URL      : https://github.com/addthis/stream-lib/archive/v2.7.0.tar.gz
Source0  : https://github.com/addthis/stream-lib/archive/v2.7.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/clearspring/analytics/stream/2.7.0/stream-2.7.0.jar
Source2  : https://repo1.maven.org/maven2/com/clearspring/analytics/stream/2.7.0/stream-2.7.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-stream-lib-data = %{version}-%{release}

%description
## Description
A Java library for summarizing data in streams for which it is
infeasible to store all events. More specifically, there are classes
for estimating: cardinality (i.e. counting things); set membership;
top-k elements and frequency.  One particularly useful feature is that
cardinality estimators with compatible configurations may be safely
merged.

%package data
Summary: data components for the mvn-stream-lib package.
Group: Data

%description data
data components for the mvn-stream-lib package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/clearspring/analytics/stream/2.7.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/clearspring/analytics/stream/2.7.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/clearspring/analytics/stream/2.7.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/clearspring/analytics/stream/2.7.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/clearspring/analytics/stream/2.7.0/stream-2.7.0.jar
/usr/share/java/.m2/repository/com/clearspring/analytics/stream/2.7.0/stream-2.7.0.pom
